### ISSUE TITLE
Material Themes

### ISSUE THREAD

**Issue by mallowigi** [rainglow/jetbrains#1]
Hi, I just discovered your repository :)

First of all great work! Up until now I've only been managing six themes and it is a huge hassle, I can't even imagine what it's like to manage 250+ color schemes, and for all editors to boot! So yeah nice work!

Secondly, I don't know if you know but I'm the new maintainer of the Material Theme UI for Jetbrains, and I'm constantly adding updates to it. I'm currently thinking of a way to let people plug their own themes as well, but it's not easy and it will probably take time. But in the meanwhile there is a "rather easy" way to add and design themes thanks to the "Custom Theme" feature of the plugin.

So if you're up to a challenge, if you have the Jetbrains IDEs installed with the plugin on your computer, you can try to meddle with the "Custom Theme" and your themes' colors and create a theme variant for each ones of your color schemes. Just check in your config directory for a file named `material_custom_theme.xml` that contains your current custom theme's colors. More info at https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/custom-themes/

Again the best way to do so would be to have a separate plugin (and thus leave the responsibility to the plugin developers like you did with the color schemes) but if you'd really want to feature a color scheme with its theme variant I'll be glad to include it as a predefined theme for the time being.

Thanks!

**Comment by daylerees** [comment]
Hey there :) I use Material UI so thanks for that! The main thing I'd love would be if Material UI adapted to the background colour of the theme. For example, there are themes for Atom and VSCode that take the background colour of the syntax theme, and use different brightness versions of that colour to theme the UI. That would go great with my themes.

Of course, it's been a long time since I set foot in Java land so I have no idea if this is feasible with the Jetbrains plugin SDKs. :)

**Comment by daylerees** [comment]
Hi again @mallowigi, on the custom themes section you linked above, is it possible to import the custom themes from files? If so, I could easily add a collection of them that would work with my theme.

**Comment by mallowigi** [comment]
Not yet. I’ll work on it as soon as I have the time but I’m the meanwhile in order to add them you need to send me the xml files and I need to convert them to java classes

Maybe there is a way to use serialization and do this automatically from a folder, looks like a nice start

**Comment by daylerees** [comment]
That makes sense. I think it might be worth exploring the serialisation. There are 325 themes in Rainglow now. It would be easy for me to generate some xml/json-rpc files with the colors for you, but if you did them manually I think you might lose the will to live. :) if the import file isn't encrypted (I can see the color definitions) then the format doesn't matter to me. Hope that helps!

**Comment by daylerees** [comment]
Hmm, actually. Can you link me to a Java class that represents a theme? Maybe I could just generate the classes. 😂

**Comment by mallowigi** [comment]
Hmm maybe it would be preferable to wait until I’ve made some advancements in the process so you can use xml files instead of java classes so you won’t need to do it again when I’ll publish it (and that would probably increase the size of the package)

Also, just changing the background is probably not enough, you need to define the selection color, contrast color, button colors and so on :)

You can try meddling with the themes if you have IntelliJ installed with Gradle, then check the MTOceanicTheme or MTCustomTheme for inspiration :)

--
Elior

**Comment by daylerees** [comment]
I'll take a look :). Finding the colours you mentioned shouldn't be an issue. I suppose another challenge would be making the toolbar drop down sane for this. Over 300 themes might break how it works currently. Hopefully we can work something out in time. I'm a PHP Dev by trade so I use your theme daily with PHPSTORM. Would be great to have them match!

**Comment by mallowigi** [comment]
You’re right I forgot about the drop down lol. It reminds me that rainglow is also kinda problematic when using the quick scheme change panel as it displays all color schemes in bulk which is suboptimal.

Maybe an improvement would be to create a setting page that could filter out unwanted color schemes

If you want I can help out with it.

--
Elior

**Comment by daylerees** [comment]
@mallowigi would you mind linking me to one of the UI theme color classes? I'd like to see how it looks, but I'm too stupid to find it. 😂

**Comment by daylerees** [comment]
Gonna close this one for now, but let's come back and make this happen. Keen to have PHPStorm looking snappy. :)
