### ISSUE TITLE
Disabling themes

### ISSUE THREAD

**Issue by mallowigi** [rainglow/jetbrains#13]
Hi,

I've installed the themes from the repository, and the first thing I saw is that it imported me the 400+ themes into my list of themes, including contrasted themes. It's good and all but it would be better to be able to actually select which themes to import.

I can do such a setting page if you want, but first I want to know if you're interested.

**Comment by perlun** [comment]
I agree. I think it would be good if the package was customized/split into multiple packages like:

- Light themes
- High-contrast themes
- Dark themes

That way, you can pick which ones you prefer.

**Comment by perlun** [comment]
@mallowigi Why was this issue closed? Has the problem been resolved?

**Comment by mallowigi** [comment]
Because it’s not likely to be done.

--
Elior
