### ISSUE TITLE
IDEA 2019.2 incorrect color scheme 

### ISSUE THREAD

**Issue by starkovsky** [rainglow/jetbrains#29]
Gloom
Peacock

**Comment by starkovsky** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10838874/61939905-062f4c00-af9d-11e9-8a28-cb148199d65d.png)

**Comment by sheraz-sarwar** [comment]
+1 on this

Seems to be working up to 2019.1.3

**Comment by starkovsky** [comment]
@daylerees Can you fix this problem? Or some reaction on issue?

**Comment by pixeloution** [comment]
I'm on 2019.2 and they seem pretty out of whack comparing to the preview theme website for rainglow (ie. https://rainglow.io/preview/#juicy)

**Comment by daylerees** [comment]
Hi guys, I'll try to make some time for this soon. @pixeloution the jetbrains themes will never look exactly like the previews unfortunately as the previews are based on VScode and there are limitations in the jetbrains theme settings that mean that parts of themes have to be the same colour for example, so it's not possible for a 1:1 match unfortunately.

@starkovsky thanks for reporting, which theme is being shown in your screenshot? I've been using them with Goland and haven't noticed this, but perhaps I've been lucky! Would love to investigate further.

**Comment by starkovsky** [comment]
@daylerees themes Gloom or Peacock
