### ISSUE TITLE
Laracasts Theme not available

### ISSUE THREAD

**Issue by Scarwolf** [rainglow/jetbrains#3]
Hi, first of all, great plugin!

But apparently the Laracasts Theme (and some others possibily) are not available when the plugin has been downloaded through the official Jetbrains PhpStorm repositories.

Here you can see a screenshot of the "rainglow.jar" contents:

![image](https://user-images.githubusercontent.com/8727623/34514144-119902d0-f06c-11e7-861c-be3778b10b67.png)

**Comment by slovenianGooner** [comment]
@Scarwolf as Dayle Rees pointed out on Twitter `https://twitter.com/daylerees/status/948483672537272320`, the plugin updates take a week or so to upgrade. Instead, you should download the .jar file from the repo and install the plugin from disk.

**Comment by Scarwolf** [comment]
Oh, thanks.
