### ISSUE TITLE
Add "Source" link on plugin page

### ISSUE THREAD

**Issue by Kendos-Kenlen** [rainglow/jetbrains#4]
Hi,

First, nice work for making all these schemes!
Second, could you add the "source" link on the plug-in page? It's currently the "vendor" link which point to this repository, but the source link make more sense so I think it's better to use it.

Have a nice day!

PS: if I can do an off topic recommendation, adding a selection tool on your website would be really nice! It would allow to find the best colour scheme depending of our colours tastes!

**Comment by daylerees** [comment]
Hey buddy, I'll do this in the next release, thanks for the tip!

As for the previews they are a bit unwieldy now, so I have something special in mind, I just have to build it. :)

Watch this space!

**Comment by daylerees** [comment]
Hey mate, do you have an example of this? Other plugins that I've checked are using vendor. :)

**Comment by Kendos-Kenlen** [comment]
Hi,

The "licensing", "sources" and "bug tracker" links can be added from the plugin' update page, not from the manifest file.

Vendor is supposed to be the creator of the plugin (you, or your company if you do that in the name of your company), so it could be the address of your GitHub profile. Then the other three are related to the plugin itself and can be links to Github.

Hope it helps!


I'm looking forward to see the evolution of your website then! I know it for a while now but never spend too much time into it because of the number of colour schemes...

**Comment by daylerees** [comment]
Thats updated now! Thanks for your help @Kendos-Kenlen :)
