### ISSUE TITLE
JS documentation tag

### ISSUE THREAD

**Issue by slovenianGooner** [rainglow/jetbrains#5]
Hi Dayle, me again, your worst nightmare 👍 

Anywho, been working on JS past few days and when documenting it I've ran into a similar issue that the Doc tag is #000000. I've tried to find it in the XML of the scheme I'm using (codecourse) but it seems it's left out altogether so PHPStorm probably defaults to that value.

![screen shot 2018-01-05 at 11 44 02](https://user-images.githubusercontent.com/1257629/34606058-2f9055c4-f20e-11e7-97f6-577043e60ca2.png)

Here's a screenshot.

**Comment by daylerees** [comment]
No worries. I'll work this out and let you know. Thanks for finding it!

**Comment by daylerees** [comment]
Hey buddy, are you using any kind of JS plugin? I've just tried with PHPStorm and the latest build and I'm struggling to replicate, see the attachment: 
![screen shot on 2018-01-07 at 00_04_41](https://user-images.githubusercontent.com/207870/34645203-1b73b37e-f33f-11e7-9b28-ed03a757858e.png)

**Comment by slovenianGooner** [comment]
Hm, not that I know of. Only 2 plugins I have installed are Rainglow and Material Theme UI, so that shouldn't be an issue. Anywho, looks like a strange issue, so I wouldn't worry about it. If you got no one else with such an issue, you can close it. I will try to uninstall the plugin and reinstall tomorrow and see if the issue remains.

**Comment by daylerees** [comment]
Let me know how it goes. :)
