### ISSUE TITLE
All rainglow themes have the same style in phpstorm 2017.3

### ISSUE THREAD

**Issue by gristoi** [rainglow/jetbrains#6]
Hi Dayle, first off great contribution, loving your work as always. I just got around to installing your plugin but am having issues with getting it to style at all. All of the themes have the same style ( below is space peacock contrast ). Am i missing an additional plugin / font set?

![screen shot 2018-01-09 at 12 37 01](https://user-images.githubusercontent.com/1233206/34721305-2f613094-f53a-11e7-82ab-65ca0a1992ee.png)

below is a screenshot of what all functions styles look like, everything in italic including namespaces, use statements and class / function names

**Comment by daylerees** [comment]
Hi there @gristoi, do you mean that function is always the same colour as public in the example?

**Comment by gristoi** [comment]
yeah, function, public, class names, use namespace, return  keywords etc all turquoise colour and italic no matter what theme i use

**Comment by daylerees** [comment]
So that colour is correct for Peacock contrast. Do you mind showing me what Glowfish looks like?

**Comment by gristoi** [comment]
ok its changing colour after i removed the material plugin and reinstalled rainglow. must have been a blip on my machine setup 👍 .
i'll close this down

**Comment by gristoi** [comment]
again, awesome piece of work :)
